export const namesOfProperties = {
  adaptability: "Adaptability",
  affection_level: "Affection Level",
  alt_names: "Alternative Names",
  cfa_url: "CFA URL",
  child_friendly: "Child Friendly",
  country_code: "Country Code",
  country_codes: "Country Codes",
  description: "Description",
  dog_friendly: "Dog Friendly",
  energy_level: "Energy Level",
  experimental: "Experimental",
  grooming: "Grooming",
  hairless: "Hairless",
  health_issues: "Health Issues",
  hypoallergenic: "Hypoallergenic",
  id: "ID",
  indoor: "Indoor",
  intelligence: "Intelligence",
  lap: "Lap",
  life_span: "Life Span",
  name: "Name",
  natural: "Natural",
  origin: "Origin",
  rare: "Rare",
  reference_image_id: "Reference Image ID",
  rex: "Rex",
  shedding_level: "Shedding Level",
  short_legs: "Short Legs",
  social_needs: "Social Needs",
  stranger_friendly: "Stranger Friendly",
  suppressed_tail: "Suppressed Tail",
  temperament: "Temperament",
  vcahospitals_url: "VCA Hospitals URL",
  vetstreet_url: "Vetstreet URL",
  vocalisation: "Vocalisation",
  weight: { imperial: "Weight - Imperial", metric: "Weight - Metric" },
  wikipedia_url: "Wikipedia URL",
};
